// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCV9P2uDbN5je9SqAZNxvY4EVKonBD-Gw',
    appId: '1:620118540071:web:986989ebc9afb0c41fb302',
    messagingSenderId: '620118540071',
    projectId: 'filmfest-218c4',
    authDomain: 'filmfest-218c4.firebaseapp.com',
    databaseURL: 'https://filmfest-218c4-default-rtdb.firebaseio.com',
    storageBucket: 'filmfest-218c4.firebasestorage.app',
    measurementId: 'G-DKVQ5T9XY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4PQ8TdSCVbHq_rfkIWF5Zbs-saXap8ZA',
    appId: '1:620118540071:android:35b97ff6be1631f01fb302',
    messagingSenderId: '620118540071',
    projectId: 'filmfest-218c4',
    databaseURL: 'https://filmfest-218c4-default-rtdb.firebaseio.com',
    storageBucket: 'filmfest-218c4.firebasestorage.app',
  );
}
